### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by ycZhang2373**
Hi we just received an notification email and now submitting it again. Thank you very much!
Yancheng Zhang
Yuling Bai

### CODE REVIEW

**Comment by zcysxy** [comment]
Hi, we cannot install `ggbiplot`. Do you install it from another source like a GitHub repository? If so, please make a comment

> If your chapter requires the installation of a package from source (is a GitHub installation), please add a comment identifying it as such. Please mention this as well in your PR.

**Comment by jtr13** [comment]
@ycZhang2373 I think the issue is that `vqv/ggbiplot` was not added to the Remotes section of `DESCRIPTION`. It needs to be both in Remotes and Suggests.

**Comment by jtr13** [comment]
Sorry I mean to tag @zcysxy 
@ycZhang2373  -- this has been merged so there's nothing else you need to do. You can close the PR you created yesterday.

**Comment by ycZhang2373** [comment]
> @ycZhang2373 -- never mind, it's a good contribution, I'm going to merge it now.

@jtr13 
Thank you professor, thank you very much!!

**Comment by zcysxy** [comment]
> @ycZhang2373 I think the issue is that `vqv/ggbiplot` was not added to the Remotes section of `DESCRIPTION`. It needs to be both in Remotes and Suggests.

Yeah, I didn't know which remote this package is from. Now it is added 🎉

**Comment by ycZhang2373** [comment]
> > @ycZhang2373 I think the issue is that `vqv/ggbiplot` was not added to the Remotes section of `DESCRIPTION`. It needs to be both in Remotes and Suggests.
> 
> Yeah, I didn't know which remote this package is from. Now it is added 🎉

Thank you so much for helping us too! So sorry for the extra work brought to you. All the best wishes!

**Pull request merged**
