### PR TITLE
Shiny app picture modify

### PR DESCRIPTION
**Pull request by wenxi77**
Hi I modify the size of images from resources but I am not sure how it would appears in the book format. Could you double check about the picture size for me? Thank you!

### CODE REVIEW

**Comment by wenxi77** [comment]
Thanks for the advice! I want to merge this pr first to see if it works! If not, I will try with your advice. Thanks!

**Comment by wenxi77** [comment]
Thank you so much! I notice the commit wasn't successful of my Merge pull request. I wonder if you can help me double check with that so that I can check the updates in the book format.

**Comment by zcysxy** [comment]
No worry! The result looks good to me <https://jtr13.github.io/cc22tt/introduction-to-shiny-web-apps.html>

**Comment by wenxi77** [comment]
Thank you! The results look good!

**Pull request merged**
