### PR TITLE
group24

### PR DESCRIPTION
**Pull request by yuqi62sss**
Stat 5702 cc group24

### CODE REVIEW

**Comment by naishadhparmar** [comment]
I merged this pull request using command line instructions and then pushed it to origin/main (the commit is [here](https://github.com/jtr13/cc22tt/commit/719a03e12029155fcd11b2e357eab1b6aea54049)), but it didn't change the status of this pull request. I have used the same strategy in the past and it worked.

@jtr13 what should be the next step here?

**Comment by jtr13** [comment]
You can merge it by just clicking the "Merge pull request" button.

**Comment by yuqi62sss** [comment]
To whom it may concern,

I see my pull request is still open. Is there anything I need to do? I am
kind of worried about the deadline if I do not finish submission work right
now.

Best,
Yuqi

**Comment by jtr13** [comment]
@yuqi62sss As you can see it's been merged now but just in general I wanted to mention that the deadline only applies to submitting the pull request since the timeline of merging is not completely in your control.

**Comment by yuqi62sss** [comment]
Thank you very much!

Yuqi

**Pull request merged**
